#!/bin/bash

# manage_my_process - indefinitely writes "I am alive!" to the file /tmp/my_process
# pauses for 2 seconds between messages

while true; do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done   
